services:
  redis:
    image: redis:alpine
    container_name: redis_sd_login_ci
    #container_name: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    networks:
      - dockernet

networks:
    dockernet:
      
  # redis:
  #   image: redis:alpine
  #   command: ["redis-server", "--bind", "redis", "--port", "6379"]